use YvrCrimeData
go


insert into Neighbourhood (Name) values ('Arbutus Ridge')
insert into Neighbourhood (Name) values ('Central Business District')
insert into Neighbourhood (Name) values ('Dunbar-Southlands')
insert into Neighbourhood (Name) values ('Fairview')
insert into Neighbourhood (Name) values ('Grandview-Woodland')
insert into Neighbourhood (Name) values ('Hastings-Sunrise')
insert into Neighbourhood (Name) values ('Kensington-Cedar Cottage')
insert into Neighbourhood (Name) values ('Kerrisdale')
insert into Neighbourhood (Name) values ('Killarney')
insert into Neighbourhood (Name) values ('Kitsilano')
insert into Neighbourhood (Name) values ('Marpole')
insert into Neighbourhood (Name) values ('Mount Pleasant')
insert into Neighbourhood (Name) values ('Musqueam')
insert into Neighbourhood (Name) values ('Oakridge')
insert into Neighbourhood (Name) values ('Renfrew-Collingwood')
insert into Neighbourhood (Name) values ('Riley Park')
insert into Neighbourhood (Name) values ('Shaughnessy')
insert into Neighbourhood (Name) values ('South Cambie')
insert into Neighbourhood (Name) values ('Stanley Park')
insert into Neighbourhood (Name) values ('Strathcona')
insert into Neighbourhood (Name) values ('Sunset')
insert into Neighbourhood (Name) values ('Victoria-Fraserview')
insert into Neighbourhood (Name) values ('West End')
insert into Neighbourhood (Name) values ('West Point Grey')
insert into Neighbourhood (Name) values ('OFFSET TO PROTECT PRIVACY')
insert into Neighbourhood (Name) values ('X NK_LOC ST')
